=== DerekVonk/Flights_DB2/FlightsBasics.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT itinerary (ticket*)>

<!ELEMENT ticket (airline, flight, departing, arriving, miles, seating,
duration)>

<!ELEMENT airline (#PCDATA)>

<!ELEMENT flight (#PCDATA)>

<!ELEMENT departing (#PCDATA)>
<!ATTLIST departing

  date  CDATA #REQUIRED
  time  CDATA #REQUIRED
  airport CDATA #REQUIRED
  gate  CDATA #IMPLIED>

<!ELEMENT arriving (#PCDATA)>
<!ATTLIST arriving
  date  CDATA #REQUIRED
  time  CDATA #REQUIRED
  airport CDATA #REQUIRED
  gate  CDATA #IMPLIED>

<!ELEMENT miles (#PCDATA)>

<!ELEMENT seating (#PCDATA)>
<!ATTLIST seating
  class  CDATA #REQUIRED
  seat  CDATA #IMPLIED>

<!ELEMENT duration (#PCDATA)>

=== DerekVonk/Flights_DB2/FlightsBasics.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- If you want to check the xml against the DTD use: -->
<!DOCTYPE itinerary SYSTEM "FlightsBasics.dtd">

<itinerary>
 <ticket>
 <airline>American</airline>
 <flight>4090</flight>
 <departing date="10-Apr-01" time="6:45AM" airport="IND" gate="A20" />
 <arriving date="10-Apr-01" time="7:52AM" airport="ORD" gate="B64" />
 <miles>168</miles>
 <seating class="Coach" seat="D3"/>
 <duration>1hr 7mn</duration>
 </ticket>
</itinerary>
